name: Run Playwright Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run Playwright Tests in CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-playwright allure-pytest pytest-xdist faker

      - name: Install Playwright browsers
        run: playwright install

      - name: Install Allure commandline
        run: npm install -g allure-commandline --save-dev

      - name: Run tests
        run: pytest -n 3 --alluredir=allure-results

      - name: Generate Allure report
        if: always()
        run: |
          if [ -d "allure-results" ]; then
            allure generate allure-results --clean -o allure-report
          else
            echo "allure-results directory not found"
            exit 1
          fi

      - name: Upload Allure report as artifact
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: allure-report
          path: allure-report

      - name: Deploy Allure Report to GitHub Pages
        if: always()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Set up git
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          
          # Check out the gh-pages branch
          git fetch origin gh-pages || git checkout --orphan gh-pages
          git worktree add gh-pages gh-pages
          cd gh-pages
          
          # Clear the gh-pages branch content
          rm -rf ./*
          
          # Copy the Allure report to the gh-pages branch
          cp -R ../allure-report/* .
          
          # Commit and push the report to the gh-pages branch
          git add .
          git commit -m "Update Allure report"
          git push origin gh-pages