name: Run Playwright Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run Playwright Tests in CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-playwright allure-pytest pytest-xdist faker

      - name: Install Playwright browsers
        run: playwright install

      - name: Run tests
        run: pytest -n 3 --alluredir=allure-results
        continue-on-error: true

      - name: Upload Allure report as artifact
        if: always()  # Ensures this step runs regardless of test success or failure
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: allure-results
